### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by varvanin** [imbasynergy/october-SPA#1]
после установки, не возможно зайти во вкладку  CMS

![Снимок экрана 2019-03-31 в 13 41 17](https://user-images.githubusercontent.com/311932/55288643-cffd0980-53ba-11e9-9003-31922c271bac.png)

**Comment by VictorTrapenok** [comment]
Добрый день.
Через 15 часов посмотрим в чём проблема

**Comment by VictorTrapenok** [comment]
Какая версия October CMS у вас стоит?

**Comment by varvanin** [comment]
System build 447

**Comment by VictorTrapenok** [comment]
Исправили, можете обновиться.
Если будут ещё проблемы обращайтесь.

**Comment by varvanin** [comment]
Добрый день. Может я что-то не так делаю, но ничего не изменилось. Также ошибка что была. Пути изменил.

**Comment by Dimasiq** [comment]
> Добрый день. Может я что-то не так делаю, но ничего не изменилось. Также ошибка что была. Пути изменил.

Добрый день, правильный путь для файлов плагина - /plugins/imbasynergy/octoberspa.
У вас так же? 
И попробуйте поменять название компонента со Spa на makeSpa, скорее всего, проблема еще и в этом.

**Comment by varvanin** [comment]
Ок

**Comment by varvanin** [comment]
/plugins/imbaSynergy/OctoberSpa  так не работало.
/plugins/imbasynergy/octoberspa  так работает. Спасибо

**Comment by VictorTrapenok** [comment]
@varvanin Плагин прошёл модерацию и теперь вы его можете поставить его из репозитория https://octobercms.com/plugin/imbasynergy-octoberspa
